#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------

version: '3'
services:
  app:
    # user: vscode
    #network_mode: host
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ../..:/workspace:cached

      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker-host.sock 
      - ~/.aws:/root/.aws:ro
      - ~/.aws:/home/node/.aws:ro
    # Uncomment the next four lines if you will use a ptrace-based debuggers like C++, Go, and Rust.
    # cap_add:
    #  - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    #entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity 
    networks: 
      - development

  dynamo:
    image: amazon/dynamodb-local
    #network_mode: host
    networks: 
      - development

networks:
  development: